### ISSUE TITLE
Task list to finalize this project

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_ms_mp2rage#9]
- [x] Train lesion segmentation model with cropped image as input  @uzaymacar 
- [x] Train model to segment the SC  https://github.com/ivadomed/model_seg_ms_mp2rage/issues/8 @uzaymacar 
- [x] Implement torchIO and the necessary data augmentation strategies in ivadomed #16
- [x] Train MS lesion segmentation model
- [x] Package model(s) into SCT's `sct_deepseg`  @jcohenadad
- [ ] Document procedure for manually fixing segmentations #14

**Comment by jcohenadad** [comment]
Completed--
